Lmod has detected the following error: The following module(s) are unknown:
"boltzmachine"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "boltzmachine"

Also make sure that all modulefiles written in TCL start with the string
#%Module




CondaError: Run 'conda init' before 'conda activate'

[H[J[3Jwandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: boltzmachine (neuroking). Use `wandb login --relogin` to force relogin
wandb: WARNING Serializing object of type list that is 166552 bytes
wandb: WARNING Serializing object of type list that is 166552 bytes
wandb: WARNING Serializing object of type list that is 173016 bytes
wandb: WARNING Serializing object of type list that is 173016 bytes
wandb: Tracking run with wandb version 0.19.0
wandb: Run data is saved locally in /gpfs/radev/project/ying_rex/wq44/samba/Samba/samba/wandb/run-20250101_005256-xljr76fz
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run young-grass-4
wandb: ‚≠êÔ∏è View project at https://wandb.ai/neuroking/samba
wandb: üöÄ View run at https://wandb.ai/neuroking/samba/runs/xljr76fz
---------------------------------------------------

       Device 0:  
           Name: NVIDIA A40 
           Memory: 44.34 GB
           ----------------               
           eleSub07_hemoSub07
           accross the subjects!
           ---------------------------------             
           Model: SambaEleToHemo--eleSub07_hemoSub07--20250101-005251--eegfmri_translation

---------------------------------------------------
Traceback (most recent call last):
  File "/gpfs/radev/project/ying_rex/wq44/samba/Samba/samba/main.py", line 147, in <module>
    training(
  File "/gpfs/radev/project/ying_rex/wq44/samba/Samba/samba/main.py", line 24, in training
    loss = model.loss(xm, xf, sub_m, sub_f, iteration)
  File "/gpfs/radev/project/ying_rex/wq44/samba/Samba/samba/model/samba_ele_to_hemo.py", line 190, in loss
    x_hemo_hat, x_hemo_hat_std, zm_hrf, alphas, h_att, h_att_std = self.forward(x_ele, x_hemo, sub_f, sub_m)
  File "/gpfs/radev/project/ying_rex/wq44/samba/Samba/samba/model/samba_ele_to_hemo.py", line 136, in forward
    x_ele_wavelet = self.temporal_encoder(x_ele_hrf.permute(0, 2, 1)).permute(0, 2, 1)  #  [10, 200, 12000]  -> [10, 200, 30]
  File "/gpfs/radev/home/wq44/.conda/envs/samba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/gpfs/radev/home/wq44/.conda/envs/samba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gpfs/radev/project/ying_rex/wq44/samba/Samba/samba/model/samba_ele_to_hemo.py", line 57, in forward
    decoder_output = self.decoder(decoder_input, hidden)
  File "/gpfs/radev/home/wq44/.conda/envs/samba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/gpfs/radev/home/wq44/.conda/envs/samba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: Mamba2.forward() takes 2 positional arguments but 3 were given
[1;34mwandb[0m: üöÄ View run [33myoung-grass-4[0m at: [34mhttps://wandb.ai/neuroking/samba/runs/xljr76fz[0m
[1;34mwandb[0m: Find logs at: [1;35mwandb/run-20250101_005256-xljr76fz/logs[0m
